cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 1
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 2
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 3
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 4
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 5
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 6
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 7
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 8
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 9
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 10
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 11
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 12
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 13
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 14
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 15
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 16
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 17
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 18
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 19
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 20  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 21  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 22  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 23  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 24  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 25  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 26  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 27  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 28  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 29  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 30
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 31
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 32
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./LR/ 33
