cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 1
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 2
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 3
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 4
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 5
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 6
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 7
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 8
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 9
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 10
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 11
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 12
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 13
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 14
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 15
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 16
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 17
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 18
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 19
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 20  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 21  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 22  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 23  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 24  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 25  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 26  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 27  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 28  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 29  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 30
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 31
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 32
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./LR.py ../data/hash_all/train.npy ../data/raw/trainLabels.npy ../data/hash_all/test.npy ./LR_hash_all/ 33
