cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 1
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 2
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 3
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 4
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 5
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 6
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 7
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 8
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 9
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 10
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 11
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 12
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 13
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 14
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 15
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 16
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 17
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 18
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 19
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 20  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 21  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 22  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 23  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 24  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 25  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 26  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 27  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 28  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 29  
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 30
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 31
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 32
cd /data/MM31/xcli/Course/ML/tradeshift/src && ./NB.py ../data/hash_str/train.npy ../data/raw/trainLabels.npy ../data/hash_str/test.npy ./NB/ 33
